<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="exports_PushId_Cert_Facade_PushIdInterfaceHttp_Service" targetNamespace="urn:mvk:asb:sso:v100:pushid" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="urn:mvk:asb:sso:v100:pushid" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="PushIdInterface_v100.wsdl" namespace="urn:mvk:asb:sso:v100:pushid"/>
  <wsdl:binding name="exports_PushId_Cert_Facade_PushIdInterfaceHttpBinding" type="this:PushIdInterface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="pushId">
      <soap:operation soapAction=""/>
      <wsdl:input name="pushIdRequest">
        <soap:header message="this:pushIdRequestMsg" part="mvkHeader"/>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output name="pushIdResponse">
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="exports_PushId_Cert_Facade_PushIdInterfaceHttpService">
    <wsdl:port binding="this:exports_PushId_Cert_Facade_PushIdInterfaceHttpBinding" name="exports_PushId_Cert_Facade_PushIdInterfaceHttpPort">
      <soap:address location="https://asbacc.minavardkontakter.se/Mvk_SSOService_CertAuthWeb/sca/exports/PushId_Cert_Facade"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>