<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="ValidateToken_ValidateTokenHttp_Service" targetNamespace="urn:mvk:asb:mvksso:ValidateToken:1:0:mvkasb10" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="urn:mvk:asb:mvksso:ValidateToken:1:0:mvkasb10" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="ValidateToken.wsdl" namespace="urn:mvk:asb:mvksso:ValidateToken:1:0:mvkasb10"/>
  <wsdl:binding name="ValidateToken_ValidateTokenHttpBinding" type="this:ValidateToken">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="validate">
      <soap:operation soapAction=""/>
      <wsdl:input name="validateRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="validateResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ValidateToken_ValidateTokenHttpService">
    <wsdl:port binding="this:ValidateToken_ValidateTokenHttpBinding" name="exports_ValidateToken_ValidateTokenHttpPort">
      <soap:address location="https://asbcacc.minavardkontakter.se/MvkAsb_ValidateIDWeb/sca/ValidateToken"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
